project:
  type: website
  output-dir: _site

website:
  title: "NFL Playoff Predictor"
  site-url: https://espiller602.github.io/stat-386-final-project
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: wrangling.qmd
        text: Data Wrangling
      - href: analysis.qmd
        text: Analysis
      - href: tutorial.qmd
        text: Tutorial
      - href: report.qmd
        text: Report
  sidebar:
    style: "docked"
    tools:
      - icon: github
        href: https://github.com/espiller602/stat-386-final-project

format:
  html:
    theme: default
    css: styles.css
    toc: true
    code-fold: show
    code-tools: true
    anchor-sections: true

